Tvp tests
v-kaywon/go-mssqldb pull request #1
Opened 2019-05-07 21:52 UTC by NikitaDef

Changed some tests.
Changed makeParamExtra `case TVP`

2019-05-09 13:40 UTC, NikitaDef commented
@v-kaywon will you merge it?

2019-05-09 18:41 UTC, yukiwongky requested changes

2019-05-09 18:41 UTC, yukiwongky commented on tvp_go19.go
>  	if len(columnStr) != len(tvpFieldIndexes) {
Can you remove this check? It's the same check as above.

2019-05-09 21:12 UTC, v-kaywon commented
@NikitaDef  Can you make the minor change mentioned above? Other than that I think everything looks good.

2019-05-13 18:20 UTC, NikitaDef commented on tvp_go19.go
>  	if len(columnStr) != len(tvpFieldIndexes) {
removed

2019-05-13 18:22 UTC, NikitaDef commented
@v-kaywon I made change

2019-05-13 18:23 UTC, merged